services:
  speech-emotion-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: speech-emotion-app:latest
    container_name: speech-emotion-app
    ports:
      - "50001:5000"
    env_file:
      - .env
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=0
    volumes:
      - .:/app
    restart: unless-stopped