version: '3.8'

services:
  speech-emotion-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: speech-emotion-app
    ports:
      - "5900:5900"
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
    volumes:
      - .:/app
    restart: unless-stopped